notify:
  name: "发送企微通消息"
  description: "通过企微通发送多种类型消息"
  fields:
    msg_type:
      name: "消息类型"
      description: "text|image|video|file|textcard|news"
      required: true
      default: "text"
      example: "textcard"
    message:
      name: "基础内容"
      description: "文本内容/卡片描述/文件描述"
      example: "传感器异常！"
    title:
      name: "标题"
      description: "用于卡片、视频和图文消息"
      example: "系统通知"
    media_id:
      name: "媒体ID"
      description: "图片/视频/文件的媒体ID（需先上传）"
      example: "1Yv-zXfHjSjU-7LH-GwtYqDGS"
    url:
      name: "链接"
      description: "卡片消息跳转链接/图文消息URL"
      example: "https://www.home-assistant.io"
    btntxt:
      name: "按钮文字"
      description: "卡片消息的按钮文字"
      default: "详情"
      example: "查看详情"
    articles:
      name: "图文列表"
      description: "图文消息的多篇文章（YAML格式）"
      example: |
        - title: "新闻标题"
          description: "新闻描述"
          url: "https://example.com"
          picurl: "https://example.com/pic.jpg"
    touser:
      name: "接收用户"
      description: "指定接收用户ID（默认为配置中的接收用户）"
      example: "@all|user1"

upload_media:
  name: "上传媒体文件"
  description: "上传文件到企微通获取media_id"
  fields:
    type:
      name: "媒体类型"
      description: "file|image|video|voice"
      required: true
      default: "file"
    file_path:
      name: "文件路径"
      description: "本地文件的完整路径"
      required: true
      example: "/config/snapshot.jpg"
    file_name:
      name: "文件名"
      description: "自定义文件名（可选）"
      example: "sensor_snapshot.jpg"
