name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Run unit tests
        run: |
          # 关键点：设置 PYTHONPATH 为当前目录
          export PYTHONPATH=$PYTHONPATH:.
          pytest -v -s ./tests/
      - name: Run unit tests
        run: pytest -v -s ./tests/
