name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration

      - name: Static analyse
        run: |
          python3 -m pip install --upgrade pip
          pip install pylint pyjwt cryptography aiohttp
          # 核心：设置路径并屏蔽干扰项
          PYTHONPATH=. pylint $(git ls-files '*.py') --disable=C0114,C0115,C0116,W0613,R0801,E0401

      - name: HA Setup Test
        id: homeassistant
        uses: ludeeus/setup-homeassistant@main
        with:
          config-dir: test_config

      - name: Install integration
        run: |
          DOMAIN=$(python3 -c "import json; import glob; print(json.load(open(glob.glob('custom_components/*/manifest.json')[0]))['domain'])")
          mkdir -p test_config/custom_components/$DOMAIN
          cp -r custom_components/$DOMAIN/* test_config/custom_components/$DOMAIN/
